name: RPM

on:
  push:
    branches: [ marine ]
  pull_request:
    branches: [ marine ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: "Cache docker build"
      uses: actions/cache@v2
      id: cache-docker
      with:
        path: '/var/lib/docker/'
        key: 'constant-because-docker-handles-cache'

    - name: "Build RPMs"
      run: cd redhat && bash ./redhat.sh

    - uses: actions/upload-artifact@v2
      with:
        path: redhat/build/packaging/rpm/RPMS/*/*.rpm

    - uses: actions/upload-artifact@v2
      with:
        path: redhat/build/packaging/rpm/SRPMS/*.rpm
